import type { Slide } from "./types";

export const slides: Slide[] = [
  {
    id: "title",
    type: "title",
    title: "Tool Tool 거리자!",
    subtitle: "도구를 숭배하지 말고, 끝까지 의심하면서 쓰자",
    durationInFrames: 120,
    tone: "dark",
  },
  {
    id: "need-vs-convenience",
    type: "statement",
    title: "필요함 vs. 편리함\n우선순위를 혼동하지 맙시다",
    subtitle: "발전은 불평에서 시작됩니다.",
    durationInFrames: 100,
    tone: "light",
  },
  {
    id: "tool-is-not-the-goal",
    type: "statement",
    title: "도구는 목적이 아니다",
    subtitle: "'삽이냐 포크레인이냐'보다는\n'왜 땅을 파야 하는가?'가 먼저",
    durationInFrames: 100,
    tone: "dark",
  },
  {
    id: "question-shift-1",
    type: "contrast",
    left: "어떤 툴이 좋아요?\n어떤 엔진이 좋아요?",
    right: "내가 해결하려는\n문제는 무엇인가?",
    durationInFrames: 110,
    tone: "light",
  },
  {
    id: "steep-learning-curve",
    type: "statement",
    title: "학습곡선이 높은 도구는\n대개 풍부하고 강력하다",
    subtitle: "하지만 매몰비용도 함께 커진다",
    durationInFrames: 100,
    tone: "dark",
  },
  {
    id: "essence-hidden",
    type: "statement",
    title: "도구를 익히다 보면\n일의 본질보다 도구가 먼저가 되는 경우가 있다",
    subtitle: "소프트웨어 생태계에서도 흔한 일이다",
    durationInFrames: 105,
    tone: "light",
  },
  {
    id: "question-shift-2",
    type: "contrast",
    left: "게임을 개발하려면\nUnity/Unreal부터 배워야 하나요?",
    right: "내가 만들고 싶은\n게임은 무엇인가?",
    durationInFrames: 110,
    tone: "dark",
  },
  {
    id: "good-tools-from-need",
    type: "statement",
    title: "좋은 도구는\n'필요'에서 발견된다",
    subtitle: "계란 프라이를 해봐야\n뒤집개의 필요성을 깨닫게 되는 것처럼",
    durationInFrames: 100,
    tone: "light",
  },
  {
    id: "need-or-opportunity",
    type: "statement",
    title: "필요한 도구가 없다면\n돈을 벌 기회가 온 것이다",
    subtitle: "이미 있다면 골라 쓸 기회가 온 것이다",
    durationInFrames: 100,
    tone: "dark",
  },
  {
    id: "naming",
    type: "statement",
    title: "좋은 이름은 결핍에서 나온다",
    subtitle: "좋은 도구는 필요에서 나오고\n좋은 이름은 결핍에서 나온다",
    durationInFrames: 100,
    tone: "light",
  },
  {
    id: "quote-hyojason",
    type: "quote",
    text: "효자손이라는 이름이 좋은 이유는\n효자도 없고, 손도 없기 때문이다",
    durationInFrames: 105,
    tone: "dark",
  },
  {
    id: "tool-notebooklm",
    type: "tool",
    index: 1,
    tool: "NotebookLM",
    url: "https://notebooklm.google.com",
    screenshot: "img/01notebooklm.png",
    useFor: "아이디어 정리와 학습/연구를 진행할 때",
    why: "맥락 안에서 사고를 확장하고 정리할 수 있어서",
    durationInFrames: 110,
    tone: "light",
  },
  {
    id: "tool-stackedit",
    type: "tool",
    index: 2,
    tool: "StackEdit",
    url: "https://stackedit.io",
    screenshot: "img/02stackedit.png",
    useFor: "Markdown과 Mermaid로 생각을 구조화할 때",
    why: "텍스트와 다이어그램을 빠르게 오가며 사고를 구체화할 수 있어서",
    durationInFrames: 110,
    tone: "dark",
  },
  {
    id: "tool-warp",
    type: "tool",
    index: 3,
    tool: "Warp",
    url: "https://warp.dev",
    screenshot: "img/03warp.png",
    useFor: "터미널 작업과 AI를 함께 활용할 때",
    why: "명령어 실행을 블록처럼 다뤄 생산성과 재사용성이 높아서",
    durationInFrames: 110,
    tone: "light",
  },
  {
    id: "tool-openrouter",
    type: "tool",
    index: 4,
    tool: "OpenRouter",
    url: "https://openrouter.ai",
    screenshot: "img/04openrouter.png",
    useFor: "여러 LLM을 상황에 맞게 사용할 때",
    why: "특정 모델에 종속되지 않고 유연하게 선택할 수 있어서",
    durationInFrames: 110,
    tone: "dark",
  },
  {
    id: "tool-stability-matrix",
    type: "tool",
    index: 5,
    tool: "Stability Matrix + ComfyUI",
    url: "https://github.com/LykosAI/StabilityMatrix",
    screenshot: "img/05stabilitymatrix.png",
    useFor: "로컬에서 이미지, 비디오, 3D 생성 작업을 할 때",
    why: "결과가 아니라 생성 과정을 직접 설계할 수 있어서",
    durationInFrames: 115,
    tone: "light",
  },
  {
    id: "tool-napkin",
    type: "tool",
    index: 6,
    tool: "Napkin",
    url: "https://napkin.ai",
    screenshot: "img/06napkin.png",
    useFor: "텍스트를 빠르게 다이어그램이나 인포그래픽으로 바꿀 때",
    why: "아이디어를 즉시 시각화하고 노가다를 줄이기 위해",
    durationInFrames: 110,
    tone: "dark",
  },
  {
    id: "tool-tweakcn",
    type: "tool",
    index: 7,
    tool: "tweakcn",
    url: "https://tweakcn.com",
    screenshot: "img/07tweakcn.png",
    useFor: "shadcn/ui 기반 디자인 테마를 빠르게 조정할 때",
    why: "디자인 시스템을 코드 기반으로 즉시 실험하고 수정할 수 있어서",
    durationInFrames: 110,
    tone: "light",
  },
  {
    id: "tool-framer",
    type: "tool",
    index: 8,
    tool: "Framer",
    url: "https://framer.com",
    screenshot: "img/08framer.png",
    useFor: "인터랙티브한 웹사이트를 빠르게 만들 때",
    why: "아이디어에서 결과물까지의 거리를 극단적으로 줄여줘서",
    durationInFrames: 110,
    tone: "dark",
  },
  {
    id: "tool-spline",
    type: "tool",
    index: 9,
    tool: "Spline.design",
    url: "https://spline.design",
    screenshot: "img/09spline.png",
    useFor: "3D 인터랙티브 디자인을 만들 때",
    why: "웹에서 바로 동작하는 3D 인터랙션을 직관적으로 설계할 수 있어서",
    durationInFrames: 110,
    tone: "light",
  },
  {
    id: "tool-remotion",
    type: "tool",
    index: 10,
    tool: "Remotion",
    url: "https://remotion.dev",
    screenshot: "img/10remotion.png",
    useFor: "모션그래픽이 풍부한 발표 자료를 코드로 만들 때",
    why: "노가다를 줄이고, procedural한 슬라이드를 만들고 싶어서",
    extra: "그리고 이 발표도 Remotion으로 만들었습니다",
    durationInFrames: 120,
    tone: "dark",
  },
  {
    id: "ending",
    type: "ending",
    title: "좋은 개발자는\n좋은 도구를 쓰는 사람이 아니다",
    subtitle: "왜 그 도구를 써야 하는지 아는 사람이다\n그러니까, 툴툴거리자",
    durationInFrames: 130,
    tone: "light",
  },
  {
    id: "qr-thanks",
    type: "qr",
    image: "img/qr_tooltool.png",
    thanks: "고맙습니다.",
    qa: "Q&A",
    durationInFrames: 120,
    tone: "dark",
  },
];

export const getSlideNavLabel = (slide: Slide) => {
  switch (slide.type) {
    case "title":
    case "statement":
    case "ending":
      return slide.title.split("\n").join(" ");
    case "contrast":
      return slide.right.split("\n").join(" ");
    case "quote":
      return slide.text.split("\n").join(" ");
    case "tool":
      return `도구 #${slide.index} ${slide.tool}`;
    case "qr":
      return slide.thanks;
    default:
      return "";
  }
};
